### ISSUE TITLE
Dismiss button doesn't work

### ISSUE THREAD

**Issue by YoniM89** [vendidero/one-stop-shop-woocommerce#1]
Clicking on "Dismiss" on either page doesn't close the "Delivery threshold reached"-message. The message keeps popping up.

**Comment by dennisnissle** [comment]
Hi there - yep, that's a bug which we've already fixed: https://github.com/vendidero/one-stop-shop-woocommerce/commit/9b8da1a82834ed3d706f44909da9274b3646beeb 
See https://wordpress.org/support/topic/delivery-threshold-reached-message-keeps-popping-up/ for additional info on that topic.

Cheers

**Comment by YoniM89** [comment]
Thanks for the info!
