### ISSUE TITLE
Potential improvement - option to use Tax name "VAT XX%" 

### ISSUE THREAD

**Issue by czjohns** [vendidero/one-stop-shop-woocommerce#2]
Hey! Thank you again for creating this plugin! I was just wondering if it'd be possible to add an option to use a different automatic Tax Name - instead of VAT COUNTRYCODE + rate type, it would be great if there was an option to use tax name in the following format: "VAT XX%".

Example:
Standard rate for HU: VAT HU -> VAT 27%
Reduced rate for HU: VAT HU reduced-rate -> VAT 5%

It would make things easier as the names are being used for invoices :)

**Comment by dennisnissle** [comment]
Hi there! The thing is that it is useful to have the country name within the tax rate description to easily detect which country the tax is being calculated on, e.g. within order screens. I've added a filter here which you may use to choose your own format here: https://github.com/vendidero/one-stop-shop-woocommerce/commit/ea6fbc97eb7d3d040ca0100ec3d1fcb9e72702c7#diff-c1857448c69e1a60418f165339fab9fc9088b25df2f70c4d37a20161c1777a30R651

Cheers
