### ISSUE TITLE
Tax classes per country not working properly for UK and FR

### ISSUE THREAD

**Issue by czjohns** [vendidero/one-stop-shop-woocommerce#3]
Hey! It's me again. 

We have started using the plugin for our live website, and have noticed a few issues regarding the Tax Classes per Country. It seems to be working fine, with the exception of UK and France, where it uses the primary product tax, which is grater increased. 

I have made several screenshots of the issue: https://imgur.com/a/mBHAXnu

Could you please look into it? Thanks!

**Comment by dennisnissle** [comment]
Hi there,

GB will only work for Northern Ireland (postcodes prefixed with BT) as GB is not part of the EU VAT zone in general. France should work just fine though.

**Comment by czjohns** [comment]
it seems to be acting strange for certain countries. Another example we found is Slovakia: 
![obrazek](https://user-images.githubusercontent.com/20816180/124452984-34238a80-dd87-11eb-90fe-7fc8be3d2454.png)
![obrazek](https://user-images.githubusercontent.com/20816180/124453050-41407980-dd87-11eb-8eec-8807c365c876.png)

**Comment by dennisnissle** [comment]
Have these orders been added via the normal Woo checkout? The default tax class is the greater reduced rate? Are you able to reproduce the issue? Please deactivate all plugins but Woo and the OSS plugin and activate a default theme for your tests. I was not yet able to reproduce such an issue.

**Comment by czjohns** [comment]
Yes, default is greater reduced rate. Orders are being done by regular customers through the checkout. 
In this case, it seems to be using the default product tax class, greater reduced, which we have set up for all the countries that don't have their individual rate set up: 
![obrazek](https://user-images.githubusercontent.com/20816180/124453725-f2dfaa80-dd87-11eb-84a9-c3516af7c601.png)
And ignoring the Standard rate set up for the SK. 

I have added 20% rate for SK to the greater reduced as a workaround for now.

**Comment by czjohns** [comment]
Had to do the same for Germany as well, it was using Greater reduced again instead of Standard. I'll be monitoring the orders and let you know if I fugure out something. 
Sadly, we are super busy with tons of other things right now, so I don't have any capacity to do the testing on test website at the moment.

**Comment by czjohns** [comment]
Hey. It really is a strange issue. We have three new France orders. Two used the incorrect, greater reduced tax and one used the correct, reduced tax. We're still looking into what causes this.

**Comment by dennisnissle** [comment]
Sounds like a caching issue - did you check that?

**Comment by czjohns** [comment]
Hey! We have probably figured out what is causing the issue. Our website is multilangual (we are using WPML) and it seems the issue with incorrect tax rate happens only when the order is made using the localized version of the website -> which also explains why the problem happens only with some Slovakia orders (when they order from CZ version), French orders (FR version) and German orders (DE version). 

Do you have any plans to add WPML compatibility by any chance?

I'd also like to ask about UK. I understand it is not supposed to work as UK is not EU VAT ZONE, but we as a store have to use their VAT rate as well. Would it be possible to add support for UK to the Tax Classes per Country feature as well? We might be able to add it ourselves, but I suspect that could break future updates. 

Thanks!

**Comment by dennisnissle** [comment]
Hi there,

the only thing I could imagine is that the meta data (tax class per country) is not being copied to the translated product object. Could you please check that? I'll add a `wpml-config.xml` file to make sure the meta gets copied on translation.

> I'd also like to ask about UK. I understand it is not supposed to work as UK is not EU VAT ZONE, but we as a store have to use their VAT rate as well. 

You might manually add their tax rates (if you need them). The OSS plugin does only add EU tax rates (and does only remove EU tax rates in case they are being re-imported) so you are safe to add UK VAT rates manually. 

Cheers

**Comment by czjohns** [comment]
Yes, we've checked and the meta data isn't copied to the translated product. We see, however, the option to add the rates to the translations manually, so we will try and see if that works. 

Regarding the UK, we added the 20% rate to the Standard rates table
![obrazek](https://user-images.githubusercontent.com/20816180/125435603-2b576c2f-6b4b-4b85-840b-8af80ead7d1c.png)
Selected Standard class in the Product settings 
![obrazek](https://user-images.githubusercontent.com/20816180/125435817-aea9782a-0516-4663-99b4-c9c68494a946.png)
But the final orders are using the primary, Greater reduced class, so I had to add the 20% rate to the Greater reduced for the UK as well, even though it is not correct. 
![obrazek](https://user-images.githubusercontent.com/20816180/125436072-70b8bceb-647c-47e0-ba45-7d3ce6221015.png)

It is basically the same problem like with the FR, SK and DE orders, but we don't have any translation for the UK, so we haven't figured out why that happens.

**Comment by dennisnissle** [comment]
Hi,

so you want to use different tax classes for UK? No, that won't work with the OSS plugin. The OSS plugin does only allow EU VAT countries here and decides based on the postcode (e.g. BT for Northern Ireland) whether an adjustment should be made or not. By default third countries (like UK) may not be taxed at all.

Cheers

**Comment by czjohns** [comment]
Hey! Yes, I understand, that's why I originally asked if it would be possible to add support for UK to the Tax Classes per Country as well, even if it isn't EU VAT country. We as a store have to use their VAT rates and the tax classes by country is a very useful feature. We might be able to add it ourselves, but I suspect that could break future plugin updates.

As for the multilanguage issue, I've just tested it and in order for it to work properly, we have to enter all the tax classes again to the translated product. After that, it seems to be working well. I'll try to set it up on our live website and see if it works there as well.

**Comment by dennisnissle** [comment]
Hi there,

I've added a filter for you which you might use to force filtering the tax class even though the plugin logic decides not to: https://github.com/vendidero/one-stop-shop-woocommerce/commit/3beb4134769e6467c860892f741bdffbad5c9e07#diff-c1857448c69e1a60418f165339fab9fc9088b25df2f70c4d37a20161c1777a30R395

Cheers

**Comment by czjohns** [comment]
Hey, thanks a lot! We'll update and test it all in the coming days!

**Comment by dennisnissle** [comment]
Just to let you know - the filter mentioned above is not yet part of the latest official release from wp.org - will be included within the next update though.
