### ISSUE TITLE
Export calculation

### ISSUE THREAD

**Issue by Patrik083** [vendidero/one-stop-shop-woocommerce#5]
Our store is inside EU. Our stores displays prices including vat. Since we have export customers (Outside EU)  we want the non vat price to be displayed. Since its a zero(0) rate tax for export. Now it displayes the same price.

To change the setup in woocomerce an pick excluding priceses insted is a lot of work since we need to insert new prices on all products.

Is it possible to have an option in OSS to deduct an percent  of specific countries (export countries) ... that would solve the problem. 
Any sugestions how to handel this.

**Comment by dennisnissle** [comment]
Hi there,

I'm not sure whether I understood what you are trying to achieve but in case you want to show net prices to customers of third countries please make sure to update to the latest version. This is a default scenario in the OSS plugin by now.

Cheers
