### ISSUE TITLE
Issue with prices in international orders

### ISSUE THREAD

**Issue by vladmirom** [vendidero/one-stop-shop-woocommerce#6]
There is an issue with the prices when ordering outside Finland. The vat rates vary in EU countries, but it was set that the product price stays the same no matter which country the customer is from. 
<img width="1259" alt="Screenshot at Sep 27 14-55-14" src="https://user-images.githubusercontent.com/13310180/134903224-e3b8bdf7-1764-406f-9dbf-78140e86a28c.png">

But now it changes the product price depending on the vat. Looks like this issue has started already in August. Also when I go to the cart and change the country, it changes the product price (Screenshots for Finalnd and Germany).
![Screenshot 2021-09-23 at 16 26 59](https://user-images.githubusercontent.com/13310180/134903468-ac796e8e-febf-4187-9d24-e6510e9173fa.png)
![Screenshot 2021-09-23 at 16 27 13](https://user-images.githubusercontent.com/13310180/134903471-c0341451-cf48-4b19-9000-d0693ef1551b.png)

One more example from the order. The product is purchased from Germany, and the price for the item is 87€, in Finland it is 109€, however, the price should be the same.
<img width="949" alt="Screenshot at Sep 27 14-59-08" src="https://user-images.githubusercontent.com/13310180/134904762-b1d7c30f-76c2-4708-a394-50d8c0fc21eb.png">

<img width="462" alt="Screenshot at Sep 27 15-02-12" src="https://user-images.githubusercontent.com/13310180/134904502-1c091921-7728-4d95-8b8d-821a9d9777b3.png">

**Comment by dennisnissle** [comment]
Hi there,

could you please try deactivating all plugins but One Stop Shop and Woo and activate a default theme (not a child-theme)? Does it fix the issue? Sounds to me as if some plugin/snippet overrides the `woocommerce_adjust_non_base_location_prices` filter. The OSS status is activated too? 

Cheers

**Comment by vladmirom** [comment]
That might be, checking.

**Comment by vladmirom** [comment]
Heya @vendidero,

It took a while to check 😅. We have disabled all the plugins (except WC and OSS) and switched to the default 2021 wp theme. The OSS status is activated. The issue is still there.

![Screenshot at Nov 08 10-47-27](https://user-images.githubusercontent.com/13310180/140711366-14522d68-49c4-48b1-be3d-0406b3e65a18.png)

**Comment by dennisnissle** [comment]
Hi there,

does that apply for customers outside of the EU? By default the fixed gross prices is only forced within the EU - third countries are not forced. If you want to force the gross price for third countries too, that would need an additional filter placed in your functions.php: https://gist.github.com/vendidero/b32ef2b031c5326915ee6a1c7674528f

Cheers

**Comment by vladmirom** [comment]
Hey, 

The price is changing both on EU and non-Eu countries. The price is different for Finland, Germany, Estonia, US, Australia.

Cheers, 
Vladimir

**Comment by dennisnissle** [comment]
Hi,

could you please provide some screenshots of your WooCommerce Tax settings? Your base country is Finland?

Cheers

**Comment by vladmirom** [comment]
A bunch of screenshots, so you can see the setup:
![Screenshot at Nov 08 13-43-25](https://user-images.githubusercontent.com/13310180/140736969-228262e0-e9fb-45f6-a6fe-729197679d28.png)
![Screenshot at Nov 08 13-43-52](https://user-images.githubusercontent.com/13310180/140736974-dc779d9b-9679-4b01-88ab-90ede984cdc4.png)
![Screenshot at Nov 08 13-46-30](https://user-images.githubusercontent.com/13310180/140736975-c271c565-ceb3-44f0-b69c-80a9560b0d0a.png)
![Screenshot at Nov 08 13-47-04](https://user-images.githubusercontent.com/13310180/140736976-5ba82f25-66ac-4395-82b5-85f17257add1.png)
![Screenshot at Nov 08 13-47-19](https://user-images.githubusercontent.com/13310180/140736977-5a4041fd-312d-4e94-9d42-e4ef2388443b.png)
![Screenshot at Nov 08 13-47-34](https://user-images.githubusercontent.com/13310180/140736980-d5de4acb-1ece-4316-8860-d8f95c03a27e.png)
![Screenshot at Nov 08 13-47-49](https://user-images.githubusercontent.com/13310180/140736982-69983e08-2090-4090-b106-5a9f28151894.png)
![Screenshot at Nov 08 13-48-02](https://user-images.githubusercontent.com/13310180/140736984-60fb1775-779f-4fdb-a34a-7391f9778e78.png)
![Screenshot at Nov 08 13-48-54](https://user-images.githubusercontent.com/13310180/140736987-554aa45b-1a60-41a2-af61-cf802aa26b6e.png)

**Comment by dennisnissle** [comment]
Could you please show a screenshot of a sample product too (edit product page)? What's your customer's default location (WooCommerce general settings)?

**Comment by vladmirom** [comment]
Here you go: 
![Screenshot at Nov 09 13-54-08](https://user-images.githubusercontent.com/13310180/140920145-4c2db971-e017-473d-b1ce-5ef454bac548.png)
![Screenshot at Nov 09 13-57-31](https://user-images.githubusercontent.com/13310180/140920150-23039eed-7048-40f1-9b00-781ef4031df4.png)

**Comment by dennisnissle** [comment]
Hi,

seems to be a variable product. Which tax classes are configured for your variations? Just want to make sure that a tax class with valid tax rates is configured for your products :)

**Comment by vladmirom** [comment]
Hi, 

it is standard or same as parent:
![Screenshot at Nov 09 14-07-28](https://user-images.githubusercontent.com/13310180/140921594-b5356447-3356-40ed-bbdb-30d627876e76.png)

**Comment by dennisnissle** [comment]
Seems ok to me. I'm not able to reproduce the issue with the latest version installed (both Woo and the OSS plugin). Could you provide us with a link to your shop?

**Comment by vladmirom** [comment]
We have a staging server for checking things on this project. I can give you the access so you can check the setup. What would be the most convenient way to send you the details?

**Comment by dennisnissle** [comment]
Please use: info@vendidero.de to contact us.

**Comment by dennisnissle** [comment]
Hi,

thanks for the dev setup. I've added some test output and it seem like calling `get_option( 'oss_fixed_gross_prices' );` returned `false` instead of `yes` - I've then reset the gross price option within the settings and set it to yes again. Now it seems to work just fine ;) Seems like a strange DB/Caching issue to me.

Cheers

**Comment by vladmirom** [comment]
Hey, thank you for working on the issue. The issue was fixed by checking out and and checking in the checkbox.
